name: Generate CDK Schema

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate_schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./
        with:
          output-path: ./generated
      
      - uses: actions/upload-artifact@v4
        with:
          name: cdk-schema-files
          path: |
            ./generated/cdk-resources.json
            ./generated/cdk-types.json